In [ ]:
#####################################################################################################
############################                     Numpy                   ############################
#####################################################################################################

In [ ]:
### 1) 0 ile 9 arasındaki tam sayıları içeren tek boyutlu bir NumPy dizisi (array) oluşturun.

import numpy as np
arr = np.arange(10, dtype=int)
print(arr)

#####################################################################################################

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
### 2) Sadece sıfırlardan oluşan 3X4 boyutlarında bir matris oluşturun.

zeros_matrix = np.zeros((3, 4), dtype=int) # 3 satır, 4 sütun
print(zeros_matrix)

#####################################################################################################

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
### 3) Sadece birlerden oluşan 2X3 boyutlarında bir matris oluşturun.

ones_matrix = np.ones((2, 3), dtype=int) #2 satır, 3 sütun
print(ones_matrix)

#####################################################################################################

[[1 1 1]
 [1 1 1]]


In [ ]:
### 4) np.arange(12).reshape(3, 4) ile oluşturulan bir dizinin boyutunu (shape), eleman sayısını (size) ve kaç boyuta sahip olduğunu (ndim) bulun.

dizi = np.arange(12).reshape(3, 4)
print( "##################")
print("Dizi:\n", dizi)
print( "##################")
print("Shape:", dizi.shape) #boyut
print( "##################")
print("Size:", dizi.size)   #eleman sayısı
print( "##################")
print("ndim:", dizi.ndim)   #boyut sayısı

#####################################################################################################

##################
Dizi:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
##################
Shape: (3, 4)
##################
Size: 12
##################
ndim: 2


In [ ]:
### 5) [10, 20, 30, 40] listesini 64-bit tam sayı (int64) veri tipinde bir NumPy dizisine dönüştürün.

liste = [10, 20, 30, 40]
np_dizi = np.array(liste, dtype=np.int64)

print( "############################")
print(np_dizi)
print( "############################")
print("Veri tipi:", np_dizi.dtype)

#####################################################################################################

############################
[10 20 30 40]
############################
Veri tipi: int64


In [ ]:
### 6) np.arange(20) dizisi içindeki 5'ten büyük ve 15'ten küçük olan tüm elemanları seçerek yeni bir dizi oluşturun.
dizi = np.arange(20)
yeni_dizi = dizi[(dizi > 5) & (dizi < 15)]

print( "###########################################################################")
print("yeni dizi:", dizi)
print( "###########################################################################")
print("5'ten büyük ve 15'ten küçük elemanlar:", yeni_dizi)

#####################################################################################################

###########################################################################
yeni dizi: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
###########################################################################
5'ten büyük ve 15'ten küçük elemanlar: [ 6  7  8  9 10 11 12 13 14]


In [ ]:
### 7) • a = np.array([1, 2, 3]) ve b = np.array([4, 5, 6]) dizilerini oluşturun.

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print( "############################")
print("a dizisi:", a)
print( "############################")
print("b dizisi:", b)

#####################################################################################################

############################
a dizisi: [1 2 3]
############################
b dizisi: [4 5 6]


In [ ]:
### 8) • Bu iki dizinin toplamını ve çarpımını (eleman bazında) hesaplayın.

toplam = a + b
carpim = a * b

print( "############################")
print("Toplam:", toplam)
print( "############################")
print("Çarpım:", carpim)

#####################################################################################################

############################
Toplam: [5 7 9]
############################
Çarpım: [ 4 10 18]


In [ ]:
### 9) M = np.arange(1, 26).reshape(5, 5) matrisini oluşturun.

M = np.arange(1, 26).reshape(5, 5)

print( "###################")
print("M matrisi:\n", M)
print( "###################")

#####################################################################################################

###################
M matrisi:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
###################


In [ ]:
### 10) Matrisin ikinci satırını ([6, 7, 8, 9, 10]) ve üçüncü sütununu ([3, 8, 13, 18, 23]) seçip ekrana yazdırın.

ikinci_satir = M[1, :]   # 2. satır (indeks 1)
ucuncu_sutun = M[:, 2]   # 3. sütun (indeks 2)

print( "##############################")
print("İkinci satır:", ikinci_satir)
print( "##############################")
print("Üçüncü sütun:", ucuncu_sutun)
print( "##############################")

#####################################################################################################

##############################
İkinci satır: [ 6  7  8  9 10]
##############################
Üçüncü sütun: [ 3  8 13 18 23]
##############################


In [ ]:
### 11) • Matris Çevirme (Transpose):

M_T = M.T  # Transpoz alma

print("####################")
print("Orijinal Matris (M):\n", M)
print("####################")
print("Transpozu (M.T):\n", M_T)
print("####################")

#####################################################################################################

####################
Orijinal Matris (M):
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
####################
Transpozu (M.T):
 [[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]
####################


In [ ]:
### 12) 3X2 boyutunda rastgele tam sayılardan oluşan bir matris oluşturun ve bu matrisin transpozunu (devriğini) alın (2 X3 olmalı).

A = np.random.randint(0, 10, size=(3, 2))
A_T = A.T

print("##########################")
print("Orijinal Matris (3x2):\n", A)
print("###########################")
print("\nTranspozu (2x3):\n", A_T)
print("###########################")

#####################################################################################################

##########################
Orijinal Matris (3x2):
 [[8 1]
 [5 7]
 [6 7]]
###########################

Transpozu (2x3):
 [[8 5 6]
 [1 7 7]]
###########################


In [ ]:
### 13) • Boş Eleman (NaN) Yönetimi:
### 14) dizi = np.array([1, 2, np.nan, 4, 5, np.nan, 7]) dizisindeki boş (NaN) eleman sayısını bulun.


dizi = np.array([1, 2, np.nan, 4, 5, np.nan, 7])
nan_sayisi = np.isnan(dizi).sum()  # NaN değer sayısını bulur

print("###################################")
print("Dizi:", dizi)
print("###################################")
print("NaN (boş) eleman sayısı:", nan_sayisi)
print("###################################")

#####################################################################################################

###################################
Dizi: [ 1.  2. nan  4.  5. nan  7.]
###################################
NaN (boş) eleman sayısı: 2
###################################


In [ ]:
### 15) 5X5 boyutlarında rastgele tam sayılardan oluşan bir matris oluşturun.

rastgele_matris = np.random.randint(0, 100, size=(5, 5))

print("######################")
print("5x5 Rastgele Matris:\n", rastgele_matris)
print("######################")

#####################################################################################################

######################
5x5 Rastgele Matris:
 [[16 80  6 15 56]
 [49 83  9  9 36]
 [ 2 33 54 79 68]
 [37 85 96  0 71]
 [24 94 54 60 26]]
######################


In [ ]:
### 16) Bu matrisin tüm elemanlarının ortalamasını, en büyük değerini ve sütun bazındaki standart sapmasını (axis=0 kullanarak) hesaplayın.

ortalama = rastgele_matris.mean()
en_buyuk = rastgele_matris.max()
std_sutun = rastgele_matris.std(axis=0)

print("######################################################################")
print("Matris:\n", rastgele_matris)
print("######################################################################")
print("Ortalama:", ortalama)
print("######################################################################")
print("En büyük değer:", en_buyuk)
print("######################################################################")
print("Standart sapma:\n", std_sutun)
print("######################################################################")

#####################################################################################################

######################################################################
Matris:
 [[16 80  6 15 56]
 [49 83  9  9 36]
 [ 2 33 54 79 68]
 [37 85 96  0 71]
 [24 94 54 60 26]]
######################################################################
Ortalama: 45.68
######################################################################
En büyük değer: 96
######################################################################
Standart sapma:
 [16.30460058 21.5127869  33.38502658 31.09083466 17.68162888]
######################################################################


In [ ]:
### 17) a = np.array([1, 2]) ve b = np.array([3, 4]) dizilerini yatay (hstack) ve dikey (vstack) olarak birleştirin.

a = np.array([1, 2])
b = np.array([3, 4])

yatay = np.hstack((a, b))
dikey = np.vstack((a, b))

print("#############################################")
print("Yatay Birleştirme (hstack):", yatay)
print("#############################################")
print("Dikey Birleştirme (vstack):\n", dikey)
print("#############################################")

#####################################################################################################

#############################################
Yatay Birleştirme (hstack): [1 2 3 4]
#############################################
Dikey Birleştirme (vstack):
 [[1 2]
 [3 4]]
#############################################


In [ ]:
### 18) A = np.array([[1, 2], [3, 4]]) ve B = np.array([[5, 6], [7, 8]]) matrislerini oluşturun.

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print( "##################")
print("A matrisi:\n", A)
print( "##################")
print("B matrisi:\n", B)
print( "##################")

#####################################################################################################

##################
A matrisi:
 [[1 2]
 [3 4]]
##################
B matrisi:
 [[5 6]
 [7 8]]
##################


In [ ]:
### 19) Bu iki matrisin matris çarpımını (dot product) hesaplayın. (Skaler çarpım değil!)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

matris_carpimi = np.dot(A, B)

print( "############################")
print("A matrisi:\n", A)
print( "############################")
print("B matrisi:\n", B)
print( "############################")
print("Matris Çarpımı (A · B):\n", matris_carpimi)
print( "############################")

#####################################################################################################

############################
A matrisi:
 [[1 2]
 [3 4]]
############################
B matrisi:
 [[5 6]
 [7 8]]
############################
Matris Çarpımı (A · B):
 [[19 22]
 [43 50]]
############################


In [ ]:
### 20) 5X5 boyutlarında rastgele bir matris oluşturun.

X = np.random.randn(5, 5)

print("##################################################################")
print("Rastgele 5x5 Matris:\n", X)
print("##################################################################")

#####################################################################################################

##################################################################
Rastgele 5x5 Matris:
 [[-0.53740269 -1.91079091  1.41541847  0.12272261 -0.23054339]
 [ 0.72398535  0.98970898 -0.69114125  0.33351398  1.15472832]
 [-0.55451494 -1.79777138  0.55761339  0.35772777 -0.18058647]
 [ 0.92580904  0.07034017 -0.42634684 -0.63314264 -0.7174745 ]
 [-0.80342112  1.22964471  1.27607982 -0.33351332 -0.96238965]]
##################################################################


In [ ]:
### 21) Bu matrisin her bir sütununa, o sütunun ortalama değerini çıkararak veriyi merkezleyin (ortalama sıfır olacak şekilde).

X = np.random.randn(5, 5)
sutun_ort = X.mean(axis=0)
X_merkezlenmis = X - sutun_ort

print("######################################################################")
print("Orijinal Matris:\n", X)
print("######################################################################")
print("Sütun Ortalamaları:\n", sutun_ort)
print("######################################################################")
print("Merkezlenmiş Matris (ortalama ≈ 0):\n", X_merkezlenmis)
print("######################################################################")

#####################################################################################################

######################################################################
Orijinal Matris:
 [[ 0.53204742 -0.75990858 -0.0979109   0.3290028   1.76382318]
 [-0.94270203  2.24975443  0.09184513  0.41701804 -2.0795089 ]
 [ 0.86159858  1.37302592  0.66101733  0.41653254  1.24225246]
 [-0.28325783  0.21616322 -1.20709212  0.72729138 -1.25751492]
 [-1.78680982 -0.89448851 -0.57983577  0.71114769 -1.33783694]]
######################################################################
Sütun Ortalamaları:
 [-0.32382474  0.4369093  -0.22639527  0.52019849 -0.33375702]
######################################################################
Merkezlenmiş Matris (ortalama ≈ 0):
 [[ 0.85587216 -1.19681787  0.12848437 -0.19119569  2.09758021]
 [-0.6188773   1.81284513  0.3182404  -0.10318045 -1.74575188]
 [ 1.18542331  0.93611662  0.8874126  -0.10366595  1.57600949]
 [ 0.04056691 -0.22074608 -0.98069686  0.20709289 -0.9237579 ]
 [-1.46298508 -1.3313978  -0.3534405   0.1909492  -1.00407992]]
#################

In [ ]:
### 22)	C = np.array([[4, 7], [2, 6]]) matrisini oluşturun.

C = np.array([[4, 7], [2, 6]])

print( "###############")
print("C matrisi:\n", C)
print( "###############")

#####################################################################################################

###############
C matrisi:
 [[4 7]
 [2 6]]
###############


In [ ]:
### 23) Matrisin determinantını hesaplayın.

C = np.array([[4, 7], [2, 6]])
det_C = np.linalg.det(C)

print( "###############################")
print("C matrisi:\n", C)
print( "###############################")
print("Determinant:", det_C)
print( "###############################")

#####################################################################################################

###############################
C matrisi:
 [[4 7]
 [2 6]]
###############################
Determinant: 10.000000000000002
###############################


In [ ]:
### 24) Matrisin tersini (inverse) hesaplayın ve ters matris ile orijinal matrisi çarparak birim matris (Identity Matrix) elde edip etmediğinizi kontrol edin.

C = np.array([[4, 7], [2, 6]])
C_inv = np.linalg.inv(C)
I = np.dot(C, C_inv)

print( "####################################")
print("C matrisi:\n", C)
print( "####################################")
print("C'nin tersi (inverse):\n", C_inv)
print( "####################################")
print("Birim Matris:\n", I)

#####################################################################################################


####################################
C matrisi:
 [[4 7]
 [2 6]]
####################################
C'nin tersi (inverse):
 [[ 0.6 -0.7]
 [-0.2  0.4]]
####################################
Birim Matris:
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


In [ ]:
### 25) veri = np.array([1, 2, 1, 4, 5, 2, 7, 1]) dizisindeki benzersiz elemanları ve her bir elemanın kaç kez tekrarlandığını bulun.

veri = np.array([1, 2, 1, 4, 5, 2, 7, 1])
benzersiz, tekrar_sayisi = np.unique(veri, return_counts=True)

print( "#######################################")
print("Benzersiz elemanlar:", benzersiz)
print( "#######################################")
print("Her elemanın tekrar sayısı:", tekrar_sayisi)
print( "#######################################")

#####################################################################################################

#######################################
Benzersiz elemanlar: [1 2 4 5 7]
#######################################
Her elemanın tekrar sayısı: [3 2 1 1 1]
#######################################


In [ ]:
### 26) dizi = np.random.randn(100) (Normal dağılımdan 100 rastgele sayı) dizisini oluşturun.

dizi = np.random.randn(100)

print("##########################################################################")
print("Normal Dağılımlı Rastgele Dizi:\n", dizi)
print("##########################################################################")

#####################################################################################################

##########################################################################
Normal Dağılımlı Rastgele Dizi:
 [-1.25886602e-01 -5.45515971e-01  2.00989111e+00 -1.19704539e-01
  2.33487181e-01  6.59920144e-01 -1.99731453e+00 -1.53438274e+00
 -2.18239500e+00 -5.51754767e-01 -8.11975372e-01 -1.96973586e-01
  1.75456202e+00 -4.18772766e-02 -1.23670832e+00  9.42311298e-01
 -4.34785103e-01 -2.58225912e-01  9.07922455e-01  3.84328571e-02
 -2.12794453e+00 -1.65137407e+00 -1.32367000e+00  1.55246504e+00
 -8.06706569e-01 -2.08605049e-01 -1.40642166e+00  1.02357066e+00
 -5.90354666e-01 -3.28594141e-01  7.76459392e-01 -1.08064351e+00
 -4.02726540e-01  1.91415390e+00  1.80986277e-01 -1.05841762e-01
 -4.14376462e-01  1.99527993e-01  4.48801375e-01 -2.82413338e-01
 -1.31006471e-03 -1.53957187e-01  9.10121398e-01 -1.01894868e+00
  5.72693752e-01 -1.68065818e+00 -1.13820852e+00 -1.57786931e-01
  5.93530483e-01 -1.12810373e+00  9.35441321e-01 -1.17814673e+00
  6.07223151e-01 -4.10922892e-01  6.00617744e-0

In [ ]:
### 27) Dizideki tüm değerleri -2 ve 2 aralığına kırpın (clip). Yani, -2'den küçük olanları -2 yapın, 2'den büyük olanları 2 yapın.

dizi = np.random.randn(100)
dizi_kirpildi = np.clip(dizi, -2, 2)

print("##########################################################################")
print("Orijinal Dizi:\n", dizi)
print("##########################################################################")
print("Kırpılmış Dizi (-2 ile 2 arası):\n", dizi_kirpildi)
print("##########################################################################")

#####################################################################################################

##########################################################################
Orijinal Dizi:
 [-1.76286153e-02 -7.82472279e-01 -5.94011546e-01  1.00693427e+00
  6.30585413e-01 -1.93954378e-01 -8.92268422e-01  3.40621573e-01
  1.74990021e+00 -4.64944970e-01 -1.26992095e+00  1.96812252e-01
  1.17101848e+00  7.36505771e-02 -5.28162041e-01  1.95964069e+00
  1.15699077e+00 -6.28701037e-01  1.85316565e+00  2.40841415e-01
 -1.48585992e-01  1.13474934e-01 -1.58976381e-01  1.81961063e+00
 -1.87806340e+00 -7.36473409e-01 -1.98197456e+00 -1.34121383e-01
  6.48077195e-01 -2.45715382e-01  9.81089107e-01 -5.75582664e-01
 -1.60330789e+00 -6.41069325e-01  3.74877252e-01  2.96875059e-02
 -4.86221767e-01 -8.81651680e-01  2.84872839e-01  5.87688221e-01
  4.35706325e-01 -1.14184968e+00  3.00434279e-01  1.06085708e-01
 -1.82882097e-02  2.29053681e-02 -7.01242898e-01  1.01661169e+00
  7.53589451e-01  1.13123672e+00  2.31383833e-01 -3.73634511e-01
  1.94165373e+00  1.66701412e-01  7.18711662e-01 -3.81230050e-02

In [ ]:
### 28) v1 = np.array([1, 2, 3]) ve v2 = np.array([4, 5, 6]) vektörlerini oluşturun.

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print( "###############")
print("v1:", v1)
print( "###############")
print("v2:", v2)
print( "###############")

#####################################################################################################

###############
v1: [1 2 3]
###############
v2: [4 5 6]
###############


In [ ]:
### 29) Bu iki vektörün nokta ürününü (inner product) ve dış ürününü (outer product) hesaplayın.


v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
nokta_urun = np.inner(v1, v2)
dis_urun = np.outer(v1, v2)

print( "###############################")
print("v1:", v1)
print( "###########################")
print("v2:", v2)
print( "###########################")
print("Nokta (inner) ürün:", nokta_urun)
print( "###########################")
print("Dış (outer) ürün:\n", dis_urun)
print( "###########################")

#####################################################################################################


###############################
v1: [1 2 3]
###########################
v2: [4 5 6]
###########################
Nokta (inner) ürün: 32
###########################
Dış (outer) ürün:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
###########################


In [ ]:
### 30) 1.000.000 elemanlı büyük bir listeyi (py_list) ve aynı elemanları içeren bir NumPy dizisini (np_array) oluşturun.

py_list = list(range(1_000_000))
np_array = np.array(py_list)

print( "###############################")
print("Python listesi uzunluğu:", len(py_list))
print( "###############################")
print("NumPy dizisi boyutu:", np_array.shape)
print( "###############################")

#####################################################################################################

###############################
Python listesi uzunluğu: 1000000
###############################
NumPy dizisi boyutu: (1000000,)
###############################


In [ ]:
#####################################################################################################
print("Mutlu Kodlamalar")
print("Gogo")
#####################################################################################################

Mutlu Kodlamalar
Gogo
